server:
  port: ${customePort:8093}

spring:
  application:
    name: RegistrationService


  rabbitmq:
    host: ${rabbitmq_host}
    port: ${rabbitmq_port:5672}
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone:  ${eureka_url:http://localhost:8761/eureka/}

  instance:
    hostname: ${HOSTNAME:${spring.application.name}}
    preferIpAddress: false
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}:${server.port}


registration_service:
  authService_uri: ${authService_uri:http://localhost:8091}