server:
  port: ${custome_port:8093}

spring:
  rabbitmq:
    host: ${rabbitmq_host:localhost}
    port: ${rabbitmq_port:5672}
    username: ${rabbitmq_user:guest}
    password: ${rabbitmq_pass:guest}
  cloud:
    bus:
      enabled: ${cloud_bus:true}
      refresh:
        enabled: ${cloud_bus_refresh:true}

eureka:
  client:
    registerWithEureka: ${registerWithEureka:true}
    fetchRegistry: ${fetchRegistry:true}
    service-url:
      defaultZone:  ${eureka_url:http://localhost:8761/eureka/}

  instance:
    hostname: ${HOSTNAME:${spring.application.name}}
    preferIpAddress: ${preferIpAddress:false}
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}:${server.port}


registration_service:
  authService_uri: ${authService_uri:http://localhost:8091}